---
apiVersion: v1
kind: Namespace
metadata:
  name: doks-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doks-example
  namespace: doks-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doks-example
  template:
    metadata:
      labels:
        app: doks-example
    spec:
      containers:
      - name: nginx
        image: digitalocean/doks-example
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: doks-example
  namespace: doks-example
spec:
  type: ClusterIP
  selector:
    app: doks-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doks-example
  namespace: doks-example
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: doks-example
            port:
              number: 80
